/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundCancellationsRouteImport } from './routes/refund-cancellations'
import { Route as ShippingDeliveryRouteImport } from './routes/shipping-delivery'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyAccountRouteImport } from './routes/verify-account'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode.index'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode.cart'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode.checkout'
import { Route as CountryCodeContactRouteImport } from './routes/$countryCode.contact'
import { Route as CountryCodePrivacyRouteImport } from './routes/$countryCode.privacy'
import { Route as CountryCodeRefundCancellationsRouteImport } from './routes/$countryCode.refund-cancellations'
import { Route as CountryCodeShippingDeliveryRouteImport } from './routes/$countryCode.shipping-delivery'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode.store'
import { Route as CountryCodeTermsRouteImport } from './routes/$countryCode.terms'
import { Route as CountryCodeVerifyAccountRouteImport } from './routes/$countryCode.verify-account'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as ApiCartRouteImport } from './routes/api.cart'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiCustomerRouteImport } from './routes/api.customer'
import { Route as ApiOrderRouteImport } from './routes/api.order'
import { Route as CategoriesHandleRouteImport } from './routes/categories.$handle'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'
import { Route as CountryCodeAccountIndexRouteImport } from './routes/$countryCode.account.index'
import { Route as CountryCodeAccountAddressesRouteImport } from './routes/$countryCode.account.addresses'
import { Route as CountryCodeAccountOrdersRouteImport } from './routes/$countryCode.account.orders'
import { Route as CountryCodeAccountProfileRouteImport } from './routes/$countryCode.account.profile'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode.categories.$handle'
import { Route as CountryCodeCollectionsHandleRouteImport } from './routes/$countryCode.collections.$handle'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode.products.$handle'
import { Route as OrderIdConfirmedRouteImport } from './routes/order.$id.confirmed'
import { Route as CountryCodeOrderIdConfirmedRouteImport } from './routes/$countryCode.order.$id.confirmed'
import { Route as AccountOrdersDetailsIdRouteImport } from './routes/account.orders.details.$id'
import { Route as CountryCodeAccountOrdersDetailsIdRouteImport } from './routes/$countryCode.account.orders.details.$id'
import { Route as OrderIdTransferTokenIndexRouteImport } from './routes/order.$id.transfer.$token.index'
import { Route as OrderIdTransferTokenAcceptRouteImport } from './routes/order.$id.transfer.$token.accept'
import { Route as OrderIdTransferTokenDeclineRouteImport } from './routes/order.$id.transfer.$token.decline'
import { Route as CountryCodeOrderIdTransferTokenIndexRouteImport } from './routes/$countryCode.order.$id.transfer.$token.index'
import { Route as CountryCodeOrderIdTransferTokenAcceptRouteImport } from './routes/$countryCode.order.$id.transfer.$token.accept'
import { Route as CountryCodeOrderIdTransferTokenDeclineRouteImport } from './routes/$countryCode.order.$id.transfer.$token.decline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundCancellationsRoute = RefundCancellationsRouteImport.update({
  id: '/refund-cancellations',
  path: '/refund-cancellations',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingDeliveryRoute = ShippingDeliveryRouteImport.update({
  id: '/shipping-delivery',
  path: '/shipping-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyAccountRoute = VerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeContactRoute = CountryCodeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodePrivacyRoute = CountryCodePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeRefundCancellationsRoute =
  CountryCodeRefundCancellationsRouteImport.update({
    id: '/refund-cancellations',
    path: '/refund-cancellations',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeShippingDeliveryRoute =
  CountryCodeShippingDeliveryRouteImport.update({
    id: '/shipping-delivery',
    path: '/shipping-delivery',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeTermsRoute = CountryCodeTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVerifyAccountRoute =
  CountryCodeVerifyAccountRouteImport.update({
    id: '/verify-account',
    path: '/verify-account',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartRoute = ApiCartRouteImport.update({
  id: '/api/cart',
  path: '/api/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerRoute = ApiCustomerRouteImport.update({
  id: '/api/customer',
  path: '/api/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderRoute = ApiOrderRouteImport.update({
  id: '/api/order',
  path: '/api/order',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesHandleRoute = CategoriesHandleRouteImport.update({
  id: '/categories/$handle',
  path: '/categories/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeAccountIndexRoute = CountryCodeAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountAddressesRoute =
  CountryCodeAccountAddressesRouteImport.update({
    id: '/account/addresses',
    path: '/account/addresses',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountOrdersRoute =
  CountryCodeAccountOrdersRouteImport.update({
    id: '/account/orders',
    path: '/account/orders',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountProfileRoute =
  CountryCodeAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCollectionsHandleRoute =
  CountryCodeCollectionsHandleRouteImport.update({
    id: '/collections/$handle',
    path: '/collections/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const OrderIdConfirmedRoute = OrderIdConfirmedRouteImport.update({
  id: '/order/$id/confirmed',
  path: '/order/$id/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeOrderIdConfirmedRoute =
  CountryCodeOrderIdConfirmedRouteImport.update({
    id: '/order/$id/confirmed',
    path: '/order/$id/confirmed',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const AccountOrdersDetailsIdRoute = AccountOrdersDetailsIdRouteImport.update({
  id: '/details/$id',
  path: '/details/$id',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const CountryCodeAccountOrdersDetailsIdRoute =
  CountryCodeAccountOrdersDetailsIdRouteImport.update({
    id: '/details/$id',
    path: '/details/$id',
    getParentRoute: () => CountryCodeAccountOrdersRoute,
  } as any)
const OrderIdTransferTokenIndexRoute =
  OrderIdTransferTokenIndexRouteImport.update({
    id: '/order/$id/transfer/$token/',
    path: '/order/$id/transfer/$token/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrderIdTransferTokenAcceptRoute =
  OrderIdTransferTokenAcceptRouteImport.update({
    id: '/order/$id/transfer/$token/accept',
    path: '/order/$id/transfer/$token/accept',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrderIdTransferTokenDeclineRoute =
  OrderIdTransferTokenDeclineRouteImport.update({
    id: '/order/$id/transfer/$token/decline',
    path: '/order/$id/transfer/$token/decline',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountryCodeOrderIdTransferTokenIndexRoute =
  CountryCodeOrderIdTransferTokenIndexRouteImport.update({
    id: '/order/$id/transfer/$token/',
    path: '/order/$id/transfer/$token/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderIdTransferTokenAcceptRoute =
  CountryCodeOrderIdTransferTokenAcceptRouteImport.update({
    id: '/order/$id/transfer/$token/accept',
    path: '/order/$id/transfer/$token/accept',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderIdTransferTokenDeclineRoute =
  CountryCodeOrderIdTransferTokenDeclineRouteImport.update({
    id: '/order/$id/transfer/$token/decline',
    path: '/order/$id/transfer/$token/decline',
    getParentRoute: () => CountryCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refund-cancellations': typeof RefundCancellationsRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/verify-account': typeof VerifyAccountRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/privacy': typeof CountryCodePrivacyRoute
  '/$countryCode/refund-cancellations': typeof CountryCodeRefundCancellationsRoute
  '/$countryCode/shipping-delivery': typeof CountryCodeShippingDeliveryRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/verify-account': typeof CountryCodeVerifyAccountRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/cart': typeof ApiCartRoute
  '/api/contact': typeof ApiContactRoute
  '/api/customer': typeof ApiCustomerRoute
  '/api/order': typeof ApiOrderRoute
  '/categories/$handle': typeof CategoriesHandleRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/account/': typeof AccountIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersRouteWithChildren
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/collections/$handle': typeof CountryCodeCollectionsHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/order/$id/confirmed': typeof OrderIdConfirmedRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/order/$id/confirmed': typeof CountryCodeOrderIdConfirmedRoute
  '/account/orders/details/$id': typeof AccountOrdersDetailsIdRoute
  '/$countryCode/account/orders/details/$id': typeof CountryCodeAccountOrdersDetailsIdRoute
  '/order/$id/transfer/$token/accept': typeof OrderIdTransferTokenAcceptRoute
  '/order/$id/transfer/$token/decline': typeof OrderIdTransferTokenDeclineRoute
  '/order/$id/transfer/$token/': typeof OrderIdTransferTokenIndexRoute
  '/$countryCode/order/$id/transfer/$token/accept': typeof CountryCodeOrderIdTransferTokenAcceptRoute
  '/$countryCode/order/$id/transfer/$token/decline': typeof CountryCodeOrderIdTransferTokenDeclineRoute
  '/$countryCode/order/$id/transfer/$token/': typeof CountryCodeOrderIdTransferTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refund-cancellations': typeof RefundCancellationsRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/verify-account': typeof VerifyAccountRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/privacy': typeof CountryCodePrivacyRoute
  '/$countryCode/refund-cancellations': typeof CountryCodeRefundCancellationsRoute
  '/$countryCode/shipping-delivery': typeof CountryCodeShippingDeliveryRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/verify-account': typeof CountryCodeVerifyAccountRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/cart': typeof ApiCartRoute
  '/api/contact': typeof ApiContactRoute
  '/api/customer': typeof ApiCustomerRoute
  '/api/order': typeof ApiOrderRoute
  '/categories/$handle': typeof CategoriesHandleRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/account': typeof AccountIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersRouteWithChildren
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/collections/$handle': typeof CountryCodeCollectionsHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/order/$id/confirmed': typeof OrderIdConfirmedRoute
  '/$countryCode/account': typeof CountryCodeAccountIndexRoute
  '/$countryCode/order/$id/confirmed': typeof CountryCodeOrderIdConfirmedRoute
  '/account/orders/details/$id': typeof AccountOrdersDetailsIdRoute
  '/$countryCode/account/orders/details/$id': typeof CountryCodeAccountOrdersDetailsIdRoute
  '/order/$id/transfer/$token/accept': typeof OrderIdTransferTokenAcceptRoute
  '/order/$id/transfer/$token/decline': typeof OrderIdTransferTokenDeclineRoute
  '/order/$id/transfer/$token': typeof OrderIdTransferTokenIndexRoute
  '/$countryCode/order/$id/transfer/$token/accept': typeof CountryCodeOrderIdTransferTokenAcceptRoute
  '/$countryCode/order/$id/transfer/$token/decline': typeof CountryCodeOrderIdTransferTokenDeclineRoute
  '/$countryCode/order/$id/transfer/$token': typeof CountryCodeOrderIdTransferTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refund-cancellations': typeof RefundCancellationsRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/verify-account': typeof VerifyAccountRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/privacy': typeof CountryCodePrivacyRoute
  '/$countryCode/refund-cancellations': typeof CountryCodeRefundCancellationsRoute
  '/$countryCode/shipping-delivery': typeof CountryCodeShippingDeliveryRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/verify-account': typeof CountryCodeVerifyAccountRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/cart': typeof ApiCartRoute
  '/api/contact': typeof ApiContactRoute
  '/api/customer': typeof ApiCustomerRoute
  '/api/order': typeof ApiOrderRoute
  '/categories/$handle': typeof CategoriesHandleRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/account/': typeof AccountIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersRouteWithChildren
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/collections/$handle': typeof CountryCodeCollectionsHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/order/$id/confirmed': typeof OrderIdConfirmedRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/order/$id/confirmed': typeof CountryCodeOrderIdConfirmedRoute
  '/account/orders/details/$id': typeof AccountOrdersDetailsIdRoute
  '/$countryCode/account/orders/details/$id': typeof CountryCodeAccountOrdersDetailsIdRoute
  '/order/$id/transfer/$token/accept': typeof OrderIdTransferTokenAcceptRoute
  '/order/$id/transfer/$token/decline': typeof OrderIdTransferTokenDeclineRoute
  '/order/$id/transfer/$token/': typeof OrderIdTransferTokenIndexRoute
  '/$countryCode/order/$id/transfer/$token/accept': typeof CountryCodeOrderIdTransferTokenAcceptRoute
  '/$countryCode/order/$id/transfer/$token/decline': typeof CountryCodeOrderIdTransferTokenDeclineRoute
  '/$countryCode/order/$id/transfer/$token/': typeof CountryCodeOrderIdTransferTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/refund-cancellations'
    | '/shipping-delivery'
    | '/store'
    | '/terms'
    | '/verify-account'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/contact'
    | '/$countryCode/privacy'
    | '/$countryCode/refund-cancellations'
    | '/$countryCode/shipping-delivery'
    | '/$countryCode/store'
    | '/$countryCode/terms'
    | '/$countryCode/verify-account'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/api/auth'
    | '/api/cart'
    | '/api/contact'
    | '/api/customer'
    | '/api/order'
    | '/categories/$handle'
    | '/collections/$handle'
    | '/products/$handle'
    | '/$countryCode/'
    | '/account/'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/products/$handle'
    | '/order/$id/confirmed'
    | '/$countryCode/account/'
    | '/$countryCode/order/$id/confirmed'
    | '/account/orders/details/$id'
    | '/$countryCode/account/orders/details/$id'
    | '/order/$id/transfer/$token/accept'
    | '/order/$id/transfer/$token/decline'
    | '/order/$id/transfer/$token/'
    | '/$countryCode/order/$id/transfer/$token/accept'
    | '/$countryCode/order/$id/transfer/$token/decline'
    | '/$countryCode/order/$id/transfer/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/refund-cancellations'
    | '/shipping-delivery'
    | '/store'
    | '/terms'
    | '/verify-account'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/contact'
    | '/$countryCode/privacy'
    | '/$countryCode/refund-cancellations'
    | '/$countryCode/shipping-delivery'
    | '/$countryCode/store'
    | '/$countryCode/terms'
    | '/$countryCode/verify-account'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/api/auth'
    | '/api/cart'
    | '/api/contact'
    | '/api/customer'
    | '/api/order'
    | '/categories/$handle'
    | '/collections/$handle'
    | '/products/$handle'
    | '/$countryCode'
    | '/account'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/products/$handle'
    | '/order/$id/confirmed'
    | '/$countryCode/account'
    | '/$countryCode/order/$id/confirmed'
    | '/account/orders/details/$id'
    | '/$countryCode/account/orders/details/$id'
    | '/order/$id/transfer/$token/accept'
    | '/order/$id/transfer/$token/decline'
    | '/order/$id/transfer/$token'
    | '/$countryCode/order/$id/transfer/$token/accept'
    | '/$countryCode/order/$id/transfer/$token/decline'
    | '/$countryCode/order/$id/transfer/$token'
  id:
    | '__root__'
    | '/'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/refund-cancellations'
    | '/shipping-delivery'
    | '/store'
    | '/terms'
    | '/verify-account'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/contact'
    | '/$countryCode/privacy'
    | '/$countryCode/refund-cancellations'
    | '/$countryCode/shipping-delivery'
    | '/$countryCode/store'
    | '/$countryCode/terms'
    | '/$countryCode/verify-account'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/api/auth'
    | '/api/cart'
    | '/api/contact'
    | '/api/customer'
    | '/api/order'
    | '/categories/$handle'
    | '/collections/$handle'
    | '/products/$handle'
    | '/$countryCode/'
    | '/account/'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/products/$handle'
    | '/order/$id/confirmed'
    | '/$countryCode/account/'
    | '/$countryCode/order/$id/confirmed'
    | '/account/orders/details/$id'
    | '/$countryCode/account/orders/details/$id'
    | '/order/$id/transfer/$token/accept'
    | '/order/$id/transfer/$token/decline'
    | '/order/$id/transfer/$token/'
    | '/$countryCode/order/$id/transfer/$token/accept'
    | '/$countryCode/order/$id/transfer/$token/decline'
    | '/$countryCode/order/$id/transfer/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundCancellationsRoute: typeof RefundCancellationsRoute
  ShippingDeliveryRoute: typeof ShippingDeliveryRoute
  StoreRoute: typeof StoreRoute
  TermsRoute: typeof TermsRoute
  VerifyAccountRoute: typeof VerifyAccountRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountProfileRoute: typeof AccountProfileRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiCartRoute: typeof ApiCartRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiCustomerRoute: typeof ApiCustomerRoute
  ApiOrderRoute: typeof ApiOrderRoute
  CategoriesHandleRoute: typeof CategoriesHandleRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  AccountIndexRoute: typeof AccountIndexRoute
  OrderIdConfirmedRoute: typeof OrderIdConfirmedRoute
  OrderIdTransferTokenAcceptRoute: typeof OrderIdTransferTokenAcceptRoute
  OrderIdTransferTokenDeclineRoute: typeof OrderIdTransferTokenDeclineRoute
  OrderIdTransferTokenIndexRoute: typeof OrderIdTransferTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-cancellations': {
      id: '/refund-cancellations'
      path: '/refund-cancellations'
      fullPath: '/refund-cancellations'
      preLoaderRoute: typeof RefundCancellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-delivery': {
      id: '/shipping-delivery'
      path: '/shipping-delivery'
      fullPath: '/shipping-delivery'
      preLoaderRoute: typeof ShippingDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-account': {
      id: '/verify-account'
      path: '/verify-account'
      fullPath: '/verify-account'
      preLoaderRoute: typeof VerifyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/contact': {
      id: '/$countryCode/contact'
      path: '/contact'
      fullPath: '/$countryCode/contact'
      preLoaderRoute: typeof CountryCodeContactRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/privacy': {
      id: '/$countryCode/privacy'
      path: '/privacy'
      fullPath: '/$countryCode/privacy'
      preLoaderRoute: typeof CountryCodePrivacyRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/refund-cancellations': {
      id: '/$countryCode/refund-cancellations'
      path: '/refund-cancellations'
      fullPath: '/$countryCode/refund-cancellations'
      preLoaderRoute: typeof CountryCodeRefundCancellationsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/shipping-delivery': {
      id: '/$countryCode/shipping-delivery'
      path: '/shipping-delivery'
      fullPath: '/$countryCode/shipping-delivery'
      preLoaderRoute: typeof CountryCodeShippingDeliveryRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/terms': {
      id: '/$countryCode/terms'
      path: '/terms'
      fullPath: '/$countryCode/terms'
      preLoaderRoute: typeof CountryCodeTermsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/verify-account': {
      id: '/$countryCode/verify-account'
      path: '/verify-account'
      fullPath: '/$countryCode/verify-account'
      preLoaderRoute: typeof CountryCodeVerifyAccountRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart': {
      id: '/api/cart'
      path: '/api/cart'
      fullPath: '/api/cart'
      preLoaderRoute: typeof ApiCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer': {
      id: '/api/customer'
      path: '/api/customer'
      fullPath: '/api/customer'
      preLoaderRoute: typeof ApiCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order': {
      id: '/api/order'
      path: '/api/order'
      fullPath: '/api/order'
      preLoaderRoute: typeof ApiOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$handle': {
      id: '/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/categories/$handle'
      preLoaderRoute: typeof CategoriesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/account/': {
      id: '/$countryCode/account/'
      path: '/account'
      fullPath: '/$countryCode/account/'
      preLoaderRoute: typeof CountryCodeAccountIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/addresses': {
      id: '/$countryCode/account/addresses'
      path: '/account/addresses'
      fullPath: '/$countryCode/account/addresses'
      preLoaderRoute: typeof CountryCodeAccountAddressesRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/orders': {
      id: '/$countryCode/account/orders'
      path: '/account/orders'
      fullPath: '/$countryCode/account/orders'
      preLoaderRoute: typeof CountryCodeAccountOrdersRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/profile': {
      id: '/$countryCode/account/profile'
      path: '/account/profile'
      fullPath: '/$countryCode/account/profile'
      preLoaderRoute: typeof CountryCodeAccountProfileRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/collections/$handle': {
      id: '/$countryCode/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/$countryCode/collections/$handle'
      preLoaderRoute: typeof CountryCodeCollectionsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/order/$id/confirmed': {
      id: '/order/$id/confirmed'
      path: '/order/$id/confirmed'
      fullPath: '/order/$id/confirmed'
      preLoaderRoute: typeof OrderIdConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/order/$id/confirmed': {
      id: '/$countryCode/order/$id/confirmed'
      path: '/order/$id/confirmed'
      fullPath: '/$countryCode/order/$id/confirmed'
      preLoaderRoute: typeof CountryCodeOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/account/orders/details/$id': {
      id: '/account/orders/details/$id'
      path: '/details/$id'
      fullPath: '/account/orders/details/$id'
      preLoaderRoute: typeof AccountOrdersDetailsIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/$countryCode/account/orders/details/$id': {
      id: '/$countryCode/account/orders/details/$id'
      path: '/details/$id'
      fullPath: '/$countryCode/account/orders/details/$id'
      preLoaderRoute: typeof CountryCodeAccountOrdersDetailsIdRouteImport
      parentRoute: typeof CountryCodeAccountOrdersRoute
    }
    '/order/$id/transfer/$token/': {
      id: '/order/$id/transfer/$token/'
      path: '/order/$id/transfer/$token'
      fullPath: '/order/$id/transfer/$token/'
      preLoaderRoute: typeof OrderIdTransferTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id/transfer/$token/accept': {
      id: '/order/$id/transfer/$token/accept'
      path: '/order/$id/transfer/$token/accept'
      fullPath: '/order/$id/transfer/$token/accept'
      preLoaderRoute: typeof OrderIdTransferTokenAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id/transfer/$token/decline': {
      id: '/order/$id/transfer/$token/decline'
      path: '/order/$id/transfer/$token/decline'
      fullPath: '/order/$id/transfer/$token/decline'
      preLoaderRoute: typeof OrderIdTransferTokenDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/order/$id/transfer/$token/': {
      id: '/$countryCode/order/$id/transfer/$token/'
      path: '/order/$id/transfer/$token'
      fullPath: '/$countryCode/order/$id/transfer/$token/'
      preLoaderRoute: typeof CountryCodeOrderIdTransferTokenIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$id/transfer/$token/accept': {
      id: '/$countryCode/order/$id/transfer/$token/accept'
      path: '/order/$id/transfer/$token/accept'
      fullPath: '/$countryCode/order/$id/transfer/$token/accept'
      preLoaderRoute: typeof CountryCodeOrderIdTransferTokenAcceptRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$id/transfer/$token/decline': {
      id: '/$countryCode/order/$id/transfer/$token/decline'
      path: '/order/$id/transfer/$token/decline'
      fullPath: '/$countryCode/order/$id/transfer/$token/decline'
      preLoaderRoute: typeof CountryCodeOrderIdTransferTokenDeclineRouteImport
      parentRoute: typeof CountryCodeRoute
    }
  }
}

interface CountryCodeAccountOrdersRouteChildren {
  CountryCodeAccountOrdersDetailsIdRoute: typeof CountryCodeAccountOrdersDetailsIdRoute
}

const CountryCodeAccountOrdersRouteChildren: CountryCodeAccountOrdersRouteChildren =
  {
    CountryCodeAccountOrdersDetailsIdRoute:
      CountryCodeAccountOrdersDetailsIdRoute,
  }

const CountryCodeAccountOrdersRouteWithChildren =
  CountryCodeAccountOrdersRoute._addFileChildren(
    CountryCodeAccountOrdersRouteChildren,
  )

interface CountryCodeRouteChildren {
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeContactRoute: typeof CountryCodeContactRoute
  CountryCodePrivacyRoute: typeof CountryCodePrivacyRoute
  CountryCodeRefundCancellationsRoute: typeof CountryCodeRefundCancellationsRoute
  CountryCodeShippingDeliveryRoute: typeof CountryCodeShippingDeliveryRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeTermsRoute: typeof CountryCodeTermsRoute
  CountryCodeVerifyAccountRoute: typeof CountryCodeVerifyAccountRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeAccountAddressesRoute: typeof CountryCodeAccountAddressesRoute
  CountryCodeAccountOrdersRoute: typeof CountryCodeAccountOrdersRouteWithChildren
  CountryCodeAccountProfileRoute: typeof CountryCodeAccountProfileRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeCollectionsHandleRoute: typeof CountryCodeCollectionsHandleRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeAccountIndexRoute: typeof CountryCodeAccountIndexRoute
  CountryCodeOrderIdConfirmedRoute: typeof CountryCodeOrderIdConfirmedRoute
  CountryCodeOrderIdTransferTokenAcceptRoute: typeof CountryCodeOrderIdTransferTokenAcceptRoute
  CountryCodeOrderIdTransferTokenDeclineRoute: typeof CountryCodeOrderIdTransferTokenDeclineRoute
  CountryCodeOrderIdTransferTokenIndexRoute: typeof CountryCodeOrderIdTransferTokenIndexRoute
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeContactRoute: CountryCodeContactRoute,
  CountryCodePrivacyRoute: CountryCodePrivacyRoute,
  CountryCodeRefundCancellationsRoute: CountryCodeRefundCancellationsRoute,
  CountryCodeShippingDeliveryRoute: CountryCodeShippingDeliveryRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeTermsRoute: CountryCodeTermsRoute,
  CountryCodeVerifyAccountRoute: CountryCodeVerifyAccountRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeAccountAddressesRoute: CountryCodeAccountAddressesRoute,
  CountryCodeAccountOrdersRoute: CountryCodeAccountOrdersRouteWithChildren,
  CountryCodeAccountProfileRoute: CountryCodeAccountProfileRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeCollectionsHandleRoute: CountryCodeCollectionsHandleRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeAccountIndexRoute: CountryCodeAccountIndexRoute,
  CountryCodeOrderIdConfirmedRoute: CountryCodeOrderIdConfirmedRoute,
  CountryCodeOrderIdTransferTokenAcceptRoute:
    CountryCodeOrderIdTransferTokenAcceptRoute,
  CountryCodeOrderIdTransferTokenDeclineRoute:
    CountryCodeOrderIdTransferTokenDeclineRoute,
  CountryCodeOrderIdTransferTokenIndexRoute:
    CountryCodeOrderIdTransferTokenIndexRoute,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

interface AccountOrdersRouteChildren {
  AccountOrdersDetailsIdRoute: typeof AccountOrdersDetailsIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersDetailsIdRoute: AccountOrdersDetailsIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  RefundCancellationsRoute: RefundCancellationsRoute,
  ShippingDeliveryRoute: ShippingDeliveryRoute,
  StoreRoute: StoreRoute,
  TermsRoute: TermsRoute,
  VerifyAccountRoute: VerifyAccountRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountProfileRoute: AccountProfileRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiCartRoute: ApiCartRoute,
  ApiContactRoute: ApiContactRoute,
  ApiCustomerRoute: ApiCustomerRoute,
  ApiOrderRoute: ApiOrderRoute,
  CategoriesHandleRoute: CategoriesHandleRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  AccountIndexRoute: AccountIndexRoute,
  OrderIdConfirmedRoute: OrderIdConfirmedRoute,
  OrderIdTransferTokenAcceptRoute: OrderIdTransferTokenAcceptRoute,
  OrderIdTransferTokenDeclineRoute: OrderIdTransferTokenDeclineRoute,
  OrderIdTransferTokenIndexRoute: OrderIdTransferTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
